# Generated by Django 2.0.6 on 2018-07-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_meal', models.CharField(max_length=200)),
                ('price_meal', models.FloatField()),
                ('availability_meal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_time', models.CharField(max_length=50)),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Place')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Time'),
        ),
    ]
