# Generated by Django 2.0.6 on 2018-07-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='tipo_meal',
            field=models.IntegerField(default=0),
        ),
    ]
