# Generated by Django 2.0.6 on 2018-07-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_meal_quantity_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='quantity_meal',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='tipo_meal',
        ),
    ]
