# Generated by Django 2.0.6 on 2018-07-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180710_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_Menu',
        ),
    ]
